/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AceEditor: typeof import('./components/Editor/AceEditor.vue')['default']
    ComponentList: typeof import('./components/ComponentList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Preview: typeof import('./components/Editor/Preview.vue')['default']
    RealTimeComponentList: typeof import('./components/RealTimeComponentList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
  }
}
